name: Deploy to Windows Dev

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  windows-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_APP_CLIENT_ID: ${{secrets.VITE_APP_CLIENT_ID}}
      VITE_APP_API_URL: ${{secrets.VITE_APP_API_URL}}
      VITE_APP_CLIENT_URL: ${{secrets.VITE_APP_CLIENT_URL}}
      VITE_APP_CLIENT_SECRET: ${{secrets.VITE_APP_CLIENT_SECRET}}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "assetdev.oc.edu"
          username: "david.north"
          key: ${{ secrets.DEV_WIN_SERVER_SSH_KEY  }}
          source: "dist/*"
          target: "c/apache24/htdocs/asset"
          tar_dereference: true
          rm: true

