name: Deploy to Windows Dev

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  windows-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_APP_CLIENT_ID: ${{secrets.VITE_APP_CLIENT_ID}}
      VITE_APP_API_URL: ${{secrets.VITE_APP_API_URL}}
      VITE_APP_CLIENT_URL: ${{secrets.VITE_APP_CLIENT_URL}}
      VITE_APP_CLIENT_SECRET: ${{secrets.VITE_APP_CLIENT_SECRET}}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: dist/
          remote: c:/Apache24/htdocs/asset
          recursive: true
          host: "asset.oc.edu"
          username: "david.north"
          privateKey: ${{ secrets.DEV_WIN_SERVER_SSH_KEY }}
